const constants = {
  MONTHS: {
    1: 'Ene',
    2: 'Feb',
    3: 'Mar',
    4: 'Abr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Ago',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dic',
  },
  PAR_LABELS: {
    minPar: 'Parámetro Mínimo',
    maxPar: 'Parámetro Máximo',
    deviationPar: 'Desviación Par',
    midPar: 'Mediana Par',
    averagePar: 'Promedio Par',
    rangePar: 'Rango Par',
  },
  SOLAR_LABELS: {
    minSolar: 'Mínimo Solar',
    maxSolar: 'Máximo Solar',
    deviationSolar: 'Desviación Solar',
    midSolar: 'Mediana Solar',
    averageSolar: 'Promedio Solar',
    rangeSolar: 'Rango Solar',
  },
  PAR_HEADER_KEYS: {
    Año: 'year',
    Mes_Numero: 'monthNumber',
    Mes: 'month',
    Estacion: 'station',
    Municipio: 'town',
    Minimo_Par: 'minPar',
    Maximo_Par: 'maxPar',
    Desviacion_Par: 'deviationPar',
    Mediana_Par: 'midPar',
    Promedio_Par: 'averagePar',
    Rango_Par: 'rangePar',
  },
  SOLAR_HEADER_KEYS: {
    Año: 'year',
    Mes_Numero: 'monthNumber',
    Mes: 'month',
    Estacion: 'station',
    Municipio: 'town',
    Minimo_Solar: 'minSolar',
    Maximo_Solar: 'maxSolar',
    Desviacion_Solar: 'deviationSolar',
    Mediana_Solar: 'midSolar',
    Promedio_Solar: 'averageSolar',
    Rango_Solar: 'rangeSolar',
  },
  HEATMAP_COLOR_VALUES: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1],
};

